// packages/vue/src/components/ui/EmptyStatePreset.vue
<script setup lang="ts">
import { computed, h, type Component } from 'vue'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'
import {
  Search,
  Database,
  Inbox,
  FolderOpen,
  Users,
  ShoppingCart,
  Bell,
  Image,
} from 'lucide-vue-next'
import EmptyState from './EmptyState.vue'
import EmptyStateIcon from './EmptyStateIcon.vue'
import EmptyStateTitle from './EmptyStateTitle.vue'
import EmptyStateDescription from './EmptyStateDescription.vue'
import EmptyStateActions from './EmptyStateActions.vue'

const emptyStateVariants = cva(
  'flex flex-col items-center justify-center text-center',
  {
    variants: {
      variant: {
        default: '',
        filled: 'bg-muted/50 rounded-none p-8',
        card: 'bg-card border-3 border-foreground shadow-[4px_4px_0px_hsl(var(--shadow-color))] p-8',
      },
      size: {
        sm: 'py-6 gap-2',
        md: 'py-8 gap-3',
        lg: 'py-12 gap-4',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  }
)

const iconContainerVariants = cva(
  'flex items-center justify-center rounded-none border-3 border-foreground mb-4',
  {
    variants: {
      iconColor: {
        default: 'bg-muted text-muted-foreground',
        primary: 'bg-primary text-primary-foreground',
        secondary: 'bg-secondary text-secondary-foreground',
        accent: 'bg-accent text-accent-foreground',
        muted: 'bg-muted/50 text-muted-foreground border-muted-foreground/50',
      },
      size: {
        sm: 'p-3',
        md: 'p-4',
        lg: 'p-5',
      },
    },
    defaultVariants: {
      iconColor: 'default',
      size: 'md',
    },
  }
)

type EmptyStateVariants = VariantProps<typeof emptyStateVariants>
type IconContainerVariants = VariantProps<typeof iconContainerVariants>

type PresetType =
  | 'no-results'
  | 'no-data'
  | 'empty-inbox'
  | 'empty-folder'
  | 'no-users'
  | 'empty-cart'
  | 'no-notifications'
  | 'no-images'

interface PresetConfig {
  icon: Component
  title: string
  description: string
}

const presets: Record<PresetType, PresetConfig> = {
  'no-results': {
    icon: Search,
    title: 'No results found',
    description: 'Try adjusting your search or filter to find what you\'re looking for.',
  },
  'no-data': {
    icon: Database,
    title: 'No data yet',
    description: 'Get started by adding your first item.',
  },
  'empty-inbox': {
    icon: Inbox,
    title: 'Your inbox is empty',
    description: 'Messages you receive will appear here.',
  },
  'empty-folder': {
    icon: FolderOpen,
    title: 'This folder is empty',
    description: 'Upload files or create new content to fill this space.',
  },
  'no-users': {
    icon: Users,
    title: 'No users found',
    description: 'Invite team members to collaborate.',
  },
  'empty-cart': {
    icon: ShoppingCart,
    title: 'Your cart is empty',
    description: 'Browse our products and add items to your cart.',
  },
  'no-notifications': {
    icon: Bell,
    title: 'All caught up!',
    description: 'You have no new notifications.',
  },
  'no-images': {
    icon: Image,
    title: 'No images yet',
    description: 'Upload images to display them here.',
  },
}

interface EmptyStatePresetProps {
  preset: PresetType
  variant?: EmptyStateVariants['variant']
  size?: EmptyStateVariants['size']
  iconColor?: IconContainerVariants['iconColor']
  class?: string
}

const props = withDefaults(defineProps<EmptyStatePresetProps>(), {
  variant: 'default',
  size: 'md',
  iconColor: 'default',
})

const config = computed(() => presets[props.preset])

const iconSizeClass = computed(() => {
  const sizes = {
    sm: 'h-8 w-8',
    md: 'h-10 w-10',
    lg: 'h-12 w-12',
  }
  return sizes[props.size || 'md']
})
</script>

<template>
  <EmptyState :variant="variant" :size="size" :class="props.class">
    <EmptyStateIcon :icon-color="iconColor" :size="size">
      <component :is="config.icon" :class="iconSizeClass" />
    </EmptyStateIcon>
    <EmptyStateTitle>{{ config.title }}</EmptyStateTitle>
    <EmptyStateDescription>{{ config.description }}</EmptyStateDescription>
    <EmptyStateActions v-if="$slots.action">
      <slot name="action" />
    </EmptyStateActions>
  </EmptyState>
</template>

// packages/svelte/src/lib/components/ui/empty-state/empty-state-preset.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import Root from './empty-state.svelte';
	import Icon from './empty-state-icon.svelte';
	import Illustration from './empty-state-illustration.svelte';
	import Title from './empty-state-title.svelte';
	import Description from './empty-state-description.svelte';
	import Actions from './empty-state-actions.svelte';
	import SearchIcon from '@lucide/svelte/icons/search';
	import FileQuestionIcon from '@lucide/svelte/icons/file-question';
	import InboxIcon from '@lucide/svelte/icons/inbox';
	import FolderOpenIcon from '@lucide/svelte/icons/folder-open';
	import UsersIcon from '@lucide/svelte/icons/users';
	import ShoppingCartIcon from '@lucide/svelte/icons/shopping-cart';
	import BellIcon from '@lucide/svelte/icons/bell';
	import ImageIcon from '@lucide/svelte/icons/image';
	import AlertTriangleIcon from '@lucide/svelte/icons/alert-triangle';
	import WifiOffIcon from '@lucide/svelte/icons/wifi-off';
	import ShieldXIcon from '@lucide/svelte/icons/shield-x';
	import ClockIcon from '@lucide/svelte/icons/clock';
	import WrenchIcon from '@lucide/svelte/icons/wrench';
	import UploadIcon from '@lucide/svelte/icons/upload';

	export type PresetType =
		| 'no-results' | 'no-data' | 'empty-inbox' | 'empty-folder' | 'no-users'
		| 'empty-cart' | 'no-notifications' | 'no-images' | 'error' | 'offline'
		| 'permission-denied' | 'coming-soon' | 'maintenance' | 'upload';

	type Props = {
		preset: PresetType;
		size?: 'sm' | 'default' | 'lg';
		customTitle?: string;
		customDescription?: string;
		class?: string;
		action?: Snippet;
		illustration?: Snippet;
	};

	let { preset, size = 'default', customTitle, customDescription, class: className, action, illustration }: Props = $props();

	type PresetConfig = { icon: typeof SearchIcon; title: string; description: string; iconColor?: string };

	const presets: Record<PresetType, PresetConfig> = {
		'no-results': { icon: SearchIcon, title: 'No results found', description: "Try adjusting your search or filter to find what you're looking for." },
		'no-data': { icon: FileQuestionIcon, title: 'No data available', description: "There's nothing to display here yet. Data will appear once available." },
		'empty-inbox': { icon: InboxIcon, title: 'Inbox is empty', description: "You're all caught up! New messages will appear here." },
		'empty-folder': { icon: FolderOpenIcon, title: 'Folder is empty', description: "This folder doesn't contain any files yet." },
		'no-users': { icon: UsersIcon, title: 'No users found', description: 'There are no users matching your criteria.' },
		'empty-cart': { icon: ShoppingCartIcon, title: 'Your cart is empty', description: "Looks like you haven't added anything to your cart yet." },
		'no-notifications': { icon: BellIcon, title: 'No notifications', description: "You're all caught up! Check back later for updates." },
		'no-images': { icon: ImageIcon, title: 'No images', description: 'There are no images to display. Upload some to get started.' },
		'error': { icon: AlertTriangleIcon, title: 'Something went wrong', description: 'An error occurred. Please try again or contact support if the problem persists.', iconColor: 'destructive' },
		'offline': { icon: WifiOffIcon, title: "You're offline", description: 'Please check your internet connection and try again.', iconColor: 'warning' },
		'permission-denied': { icon: ShieldXIcon, title: 'Access denied', description: "You don't have permission to view this content.", iconColor: 'destructive' },
		'coming-soon': { icon: ClockIcon, title: 'Coming soon', description: 'This feature is under development. Stay tuned for updates!', iconColor: 'accent' },
		'maintenance': { icon: WrenchIcon, title: 'Under maintenance', description: "We're performing scheduled maintenance. Please check back soon.", iconColor: 'warning' },
		'upload': { icon: UploadIcon, title: 'Upload files', description: 'Drag and drop files here, or click to browse.', iconColor: 'primary' },
	};

	const config = $derived(presets[preset]);
	const iconSizeClass = $derived(size === 'sm' ? 'h-6 w-6' : size === 'lg' ? 'h-10 w-10' : 'h-8 w-8');
</script>

<Root {size} class={className}>
	{#if illustration}
		<Illustration>{@render illustration()}</Illustration>
	{:else}
		<Icon>
			<config.icon class={iconSizeClass} />
		</Icon>
	{/if}
	<div>
		<Title>{customTitle ?? config.title}</Title>
		<Description>{customDescription ?? config.description}</Description>
		{#if action}
			<Actions>{@render action()}</Actions>
		{/if}
	</div>
</Root>
