// src/components/ui/tree-view.tsx
import * as React from 'react'
import { ChevronRight, Folder, File } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible'

export interface TreeNode {
  id: string
  label: string
  icon?: React.ReactNode
  children?: TreeNode[]
  disabled?: boolean
}

export interface TreeViewProps extends React.HTMLAttributes<HTMLDivElement> {
  data: TreeNode[]
  expandedIds?: string[]
  onExpandedChange?: (ids: string[]) => void
  selectedIds?: string[]
  onSelectedChange?: (ids: string[]) => void
  selectionMode?: 'none' | 'single' | 'multiple'
  showCheckboxes?: boolean
  showIcons?: boolean
  defaultExpandedIds?: string[]
  defaultSelectedIds?: string[]
}

// Context
interface TreeViewContextValue {
  expandedIds: Set<string>
  toggleExpanded: (id: string) => void
  selectedIds: Set<string>
  toggleSelected: (id: string) => void
  selectionMode: 'none' | 'single' | 'multiple'
  showCheckboxes: boolean
  showIcons: boolean
}

const TreeViewContext = React.createContext<TreeViewContextValue | null>(null)

function useTreeView() {
  const context = React.useContext(TreeViewContext)
  if (!context) {
    throw new Error('TreeView components must be used within a <TreeView />')
  }
  return context
}

const TreeView = React.forwardRef<HTMLDivElement, TreeViewProps>(
  (
    {
      data,
      expandedIds: controlledExpandedIds,
      onExpandedChange,
      selectedIds: controlledSelectedIds,
      onSelectedChange,
      selectionMode = 'none',
      showCheckboxes = false,
      showIcons = true,
      defaultExpandedIds = [],
      defaultSelectedIds = [],
      className,
      ...props
    },
    ref
  ) => {
    const [uncontrolledExpandedIds, setUncontrolledExpandedIds] = React.useState<Set<string>>(
      new Set(defaultExpandedIds)
    )
    const [uncontrolledSelectedIds, setUncontrolledSelectedIds] = React.useState<Set<string>>(
      new Set(defaultSelectedIds)
    )

    const isExpandedControlled = controlledExpandedIds !== undefined
    const isSelectedControlled = controlledSelectedIds !== undefined

    // Memoize Set objects to prevent useCallback dependencies from changing on every render
    const expandedIds = React.useMemo(
      () => (isExpandedControlled ? new Set(controlledExpandedIds) : uncontrolledExpandedIds),
      [isExpandedControlled, controlledExpandedIds, uncontrolledExpandedIds]
    )

    const selectedIds = React.useMemo(
      () => (isSelectedControlled ? new Set(controlledSelectedIds) : uncontrolledSelectedIds),
      [isSelectedControlled, controlledSelectedIds, uncontrolledSelectedIds]
    )

    const toggleExpanded = React.useCallback(
      (id: string) => {
        const newExpandedIds = new Set(expandedIds)
        if (newExpandedIds.has(id)) {
          newExpandedIds.delete(id)
        } else {
          newExpandedIds.add(id)
        }

        if (!isExpandedControlled) {
          setUncontrolledExpandedIds(newExpandedIds)
        }
        onExpandedChange?.(Array.from(newExpandedIds))
      },
      [expandedIds, isExpandedControlled, onExpandedChange]
    )

    const toggleSelected = React.useCallback(
      (id: string) => {
        if (selectionMode === 'none') return

        let newSelectedIds: Set<string>

        if (selectionMode === 'single') {
          newSelectedIds = selectedIds.has(id) ? new Set() : new Set([id])
        } else {
          newSelectedIds = new Set(selectedIds)
          if (newSelectedIds.has(id)) {
            newSelectedIds.delete(id)
          } else {
            newSelectedIds.add(id)
          }
        }

        if (!isSelectedControlled) {
          setUncontrolledSelectedIds(newSelectedIds)
        }
        onSelectedChange?.(Array.from(newSelectedIds))
      },
      [selectedIds, selectionMode, isSelectedControlled, onSelectedChange]
    )

    return (
      <TreeViewContext.Provider
        value={{
          expandedIds,
          toggleExpanded,
          selectedIds,
          toggleSelected,
          selectionMode,
          showCheckboxes,
          showIcons,
        }}
      >
        <div
          ref={ref}
          role="tree"
          className={cn(
            'border-3 border-foreground bg-background p-2',
            'shadow-[4px_4px_0px_hsl(var(--shadow-color))]',
            className
          )}
          {...props}
        >
          {data.map((node) => (
            <TreeNode key={node.id} node={node} level={0} />
          ))}
        </div>
      </TreeViewContext.Provider>
    )
  }
)
TreeView.displayName = 'TreeView'

// Tree Node Component
interface TreeNodeProps {
  node: TreeNode
  level: number
}

function TreeNode({ node, level }: TreeNodeProps) {
  const {
    expandedIds,
    toggleExpanded,
    selectedIds,
    toggleSelected,
    selectionMode,
    showCheckboxes,
    showIcons,
  } = useTreeView()

  const hasChildren = node.children && node.children.length > 0
  const isExpanded = expandedIds.has(node.id)
  const isSelected = selectedIds.has(node.id)

  const handleKeyDown = (e: React.KeyboardEvent) => {
    switch (e.key) {
      case 'Enter':
      case ' ':
        e.preventDefault()
        if (selectionMode !== 'none') {
          toggleSelected(node.id)
        } else if (hasChildren) {
          toggleExpanded(node.id)
        }
        break
      case 'ArrowRight':
        if (hasChildren && !isExpanded) {
          e.preventDefault()
          toggleExpanded(node.id)
        }
        break
      case 'ArrowLeft':
        if (hasChildren && isExpanded) {
          e.preventDefault()
          toggleExpanded(node.id)
        }
        break
    }
  }

  const content = (
    <div
      role="treeitem"
      aria-selected={isSelected}
      aria-expanded={hasChildren ? isExpanded : undefined}
      aria-disabled={node.disabled}
      tabIndex={node.disabled ? -1 : 0}
      onKeyDown={handleKeyDown}
      onClick={() => {
        if (node.disabled) return
        if (selectionMode !== 'none') {
          toggleSelected(node.id)
        }
      }}
      className={cn(
        'flex items-center gap-2 px-2 py-1.5 cursor-pointer transition-colors',
        'hover:bg-muted focus:outline-none focus:bg-muted',
        isSelected && 'bg-accent',
        node.disabled && 'opacity-50 cursor-not-allowed'
      )}
      style={{ paddingLeft: `${level * 16 + 8}px` }}
    >
      {/* Expand/collapse button */}
      {hasChildren ? (
        <button
          type="button"
          onClick={(e) => {
            e.stopPropagation()
            toggleExpanded(node.id)
          }}
          className="p-0.5 hover:bg-muted-foreground/20 transition-colors"
          aria-label={isExpanded ? 'Collapse' : 'Expand'}
        >
          <ChevronRight
            className={cn(
              'h-4 w-4 stroke-[3] transition-transform duration-200',
              isExpanded && 'rotate-90'
            )}
          />
        </button>
      ) : (
        <span className="w-5" />
      )}

      {/* Checkbox */}
      {showCheckboxes && selectionMode !== 'none' && (
        <Checkbox
          checked={isSelected}
          onCheckedChange={() => toggleSelected(node.id)}
          onClick={(e) => e.stopPropagation()}
          disabled={node.disabled}
          className="h-5 w-5 border-2 border-foreground data-[state=checked]:bg-primary data-[state=checked]:shadow-[2px_2px_0px_hsl(var(--shadow-color))]"
        />
      )}

      {/* Icon */}
      {showIcons && (
        <span className="shrink-0">
          {node.icon || (hasChildren ? (
            <Folder className="h-4 w-4" />
          ) : (
            <File className="h-4 w-4" />
          ))}
        </span>
      )}

      {/* Label */}
      <span className="text-sm truncate">{node.label}</span>
    </div>
  )

  if (!hasChildren) {
    return content
  }

  return (
    <Collapsible open={isExpanded} onOpenChange={() => toggleExpanded(node.id)}>
      <CollapsibleTrigger asChild className="w-full">
        {content}
      </CollapsibleTrigger>
      <CollapsibleContent>
        <div role="group">
          {node.children!.map((child) => (
            <TreeNode key={child.id} node={child} level={level + 1} />
          ))}
        </div>
      </CollapsibleContent>
    </Collapsible>
  )
}

export { TreeView, useTreeView }

// packages/svelte/src/lib/components/ui/tree-view/tree-view.svelte
<script lang="ts">
	import ChevronRightIcon from '@lucide/svelte/icons/chevron-right';
	import FileIcon from '@lucide/svelte/icons/file';
	import FolderIcon from '@lucide/svelte/icons/folder';
	import { cn } from '$lib/utils.js';

	export type TreeNode = {
		id: string;
		label: string;
		children?: TreeNode[];
		disabled?: boolean;
	};

	type Props = {
		data?: TreeNode[];
		defaultExpandedIds?: string[];
		defaultSelectedIds?: string[];
		selectionMode?: 'none' | 'single' | 'multiple';
		showIcons?: boolean;
		class?: string;
		onExpandedChange?: (ids: string[]) => void;
		onSelectedChange?: (ids: string[]) => void;
	};

	let {
		data = [],
		defaultExpandedIds = [],
		defaultSelectedIds = [],
		selectionMode = 'none',
		showIcons = true,
		class: className,
		onExpandedChange,
		onSelectedChange,
	}: Props = $props();

	let expandedIds = $state<Set<string> | undefined>(undefined);
	let selectedIds = $state<Set<string> | undefined>(undefined);
	const currentExpandedIds = $derived(expandedIds ?? new Set(defaultExpandedIds));
	const currentSelectedIds = $derived(selectedIds ?? new Set(defaultSelectedIds));

	function toggleExpanded(id: string) {
		expandedIds = new Set(currentExpandedIds);
		expandedIds.has(id) ? expandedIds.delete(id) : expandedIds.add(id);
		onExpandedChange?.([...expandedIds]);
	}

	function toggleSelected(id: string) {
		if (selectionMode === 'none') return;
		if (selectionMode === 'single') {
			selectedIds = currentSelectedIds.has(id) ? new Set() : new Set([id]);
		} else {
			selectedIds = new Set(currentSelectedIds);
			selectedIds.has(id) ? selectedIds.delete(id) : selectedIds.add(id);
		}
		onSelectedChange?.([...selectedIds]);
	}
</script>

{#snippet NodeItem(node: TreeNode, level: number)}
	{@const hasChildren = Boolean(node.children?.length)}
	{@const isExpanded = currentExpandedIds.has(node.id)}
	{@const isSelected = currentSelectedIds.has(node.id)}
	<div>
		<button
			type="button"
			role="treeitem"
			aria-selected={isSelected}
			aria-expanded={hasChildren ? isExpanded : undefined}
			disabled={node.disabled}
			class={cn(
				'flex w-full items-center gap-2 px-2 py-1.5 text-left text-sm font-bold transition-colors hover:bg-muted disabled:cursor-not-allowed disabled:opacity-50',
				isSelected && 'bg-primary text-primary-foreground'
			)}
			style={`padding-left: ${level * 18 + 8}px`}
			onclick={() => hasChildren ? toggleExpanded(node.id) : toggleSelected(node.id)}
			ondblclick={() => toggleSelected(node.id)}
		>
			{#if hasChildren}
				<ChevronRightIcon class={cn('h-4 w-4 transition-transform', isExpanded && 'rotate-90')} />
			{:else}
				<span class="h-4 w-4"></span>
			{/if}
			{#if showIcons}
				{#if hasChildren}
					<FolderIcon class="h-4 w-4" />
				{:else}
					<FileIcon class="h-4 w-4" />
				{/if}
			{/if}
			<span>{node.label}</span>
		</button>
		{#if hasChildren && isExpanded}
			{#each node.children ?? [] as child (child.id)}
				{@render NodeItem(child, level + 1)}
			{/each}
		{/if}
	</div>
{/snippet}

<div role="tree" class={cn('border-3 border-foreground bg-background p-2 shadow-[4px_4px_0px_hsl(var(--shadow-color))]', className)}>
	{#each data as node (node.id)}
		{@render NodeItem(node, 0)}
	{/each}
</div>
