// src/components/CanvasEffects/react/MouseRipple.tsx
import { useEffect, useRef, type CSSProperties } from 'react'

export interface MouseRippleProps {
  /** Dot fill color */
  color?: string
  /** Distance between dot centers in px */
  gap?: number
  /** Radius of the ripple influence zone in px */
  rippleRadius?: number
  /** Ripple wave speed multiplier */
  speed?: number
  className?: string
  style?: CSSProperties
}

/**
 * MouseRipple — Interactive dot-grid ripple
 *
 * Move the mouse over the canvas to send a sine ripple through
 * the dot grid. Dots outside the cursor zone stay at rest.
 *
 * @example
 * <MouseRipple color="#f59e0b" gap={24} rippleRadius={130} speed={1} />
 */
export function MouseRipple({
  color = '#f59e0b',
  gap = 24,
  rippleRadius = 130,
  speed = 1,
  className,
  style,
}: MouseRippleProps) {
  const ref           = useRef<HTMLCanvasElement>(null)
  const mouse         = useRef({ x: -999, y: -999 })
  const colorRef      = useRef(color)
  const gapRef        = useRef(gap)
  const radiusRef     = useRef(rippleRadius)
  const speedRef      = useRef(speed)

  useEffect(() => { colorRef.current  = color        }, [color])
  useEffect(() => { gapRef.current    = gap          }, [gap])
  useEffect(() => { radiusRef.current = rippleRadius }, [rippleRadius])
  useEffect(() => { speedRef.current  = speed        }, [speed])

  useEffect(() => {
    const el = ref.current
    if (!el) return
    const ctx = el.getContext('2d')!
    let raf = 0
    const resize = () => {
      const dpr = window.devicePixelRatio || 1
      el.width = el.offsetWidth * dpr
      el.height = el.offsetHeight * dpr
    }
    resize()

    const onMove = (e: MouseEvent) => {
      const r = el.getBoundingClientRect()
      const dpr = window.devicePixelRatio || 1
      mouse.current = { x: (e.clientX - r.left) * dpr, y: (e.clientY - r.top) * dpr }
    }
    el.addEventListener('mousemove', onMove)

    let t = 0
    const draw = () => {
      const dpr = window.devicePixelRatio || 1
      const GAP = gapRef.current * dpr
      const W = el.width, H = el.height
      ctx.clearRect(0, 0, W, H)
      const cols = Math.ceil(W / GAP) + 1, rows = Math.ceil(H / GAP) + 1
      const { x: mx, y: my } = mouse.current
      const RAD = radiusRef.current * dpr

      for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) {
          const cx = c * GAP + GAP / 2, cy = r * GAP + GAP / 2
          const dx = cx - mx, dy = cy - my
          const dist = Math.sqrt(dx * dx + dy * dy)
          const ripple = Math.max(0, 1 - dist / RAD) * Math.sin(dist * 0.14 - t * 3.2)
          const size = Math.max(0, 3 + ripple * 9)
          ctx.globalAlpha = Math.max(0.1, Math.min(1, 0.25 + Math.abs(ripple) * 0.75))
          ctx.fillStyle = colorRef.current
          ctx.fillRect(cx - size / 2, cy - size / 2, size, size)
        }
      }

      ctx.globalAlpha = 1
      t += 0.06 * speedRef.current
      raf = requestAnimationFrame(draw)
    }

    draw()
    const ro = new ResizeObserver(resize)
    ro.observe(el)
    return () => {
      cancelAnimationFrame(raf); ro.disconnect()
      el.removeEventListener('mousemove', onMove)
    }
  }, [])

  return (
    <canvas
      ref={ref}
      className={className}
      style={{ display: 'block', width: '100%', height: '100%', cursor: 'crosshair', ...style }}
    />
  )
}

// src/components/CanvasEffects/vue/MouseRipple.vue
<script setup lang="ts">
/**
 * MouseRipple — Interactive dot-grid ripple
 * Compatible with Vue 3 and Nuxt 3.
 *
 * @example
 * <MouseRipple color="#f59e0b" :gap="24" :ripple-radius="130" :speed="1" />
 */
import { ref, onMounted, onUnmounted } from 'vue'

const props = withDefaults(defineProps<{
  color?: string
  gap?: number
  rippleRadius?: number
  speed?: number
}>(), { color: '#f59e0b', gap: 24, rippleRadius: 130, speed: 1 })

const canvasRef = ref<HTMLCanvasElement | null>(null)
let raf = 0
let ro: ResizeObserver | null = null
let cleanupMouse: (() => void) | null = null

onMounted(() => {
  const el = canvasRef.value
  if (!el) return
  const ctx = el.getContext('2d')!
  const mouse = { x: -999, y: -999 }

  const resize = () => { const dpr = window.devicePixelRatio || 1; el.width = el.offsetWidth * dpr; el.height = el.offsetHeight * dpr }
  resize()

  const onMove = (e: MouseEvent) => {
    const r = el.getBoundingClientRect()
    const dpr = window.devicePixelRatio || 1
    mouse.x = (e.clientX - r.left) * dpr; mouse.y = (e.clientY - r.top) * dpr
  }
  el.addEventListener('mousemove', onMove)
  cleanupMouse = () => el.removeEventListener('mousemove', onMove)

  let t = 0
  const draw = () => {
    const dpr = window.devicePixelRatio || 1
    const GAP = props.gap * dpr, W = el.width, H = el.height, RAD = props.rippleRadius * dpr
    ctx.clearRect(0, 0, W, H)
    const cols = Math.ceil(W / GAP) + 1, rows = Math.ceil(H / GAP) + 1
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        const cx = c * GAP + GAP / 2, cy = r * GAP + GAP / 2
        const dx = cx - mouse.x, dy = cy - mouse.y
        const dist = Math.sqrt(dx * dx + dy * dy)
        const ripple = Math.max(0, 1 - dist / RAD) * Math.sin(dist * 0.14 - t * 3.2)
        const size = Math.max(0, 3 + ripple * 9)
        ctx.globalAlpha = Math.max(0.1, Math.min(1, 0.25 + Math.abs(ripple) * 0.75))
        ctx.fillStyle = props.color
        ctx.fillRect(cx - size / 2, cy - size / 2, size, size)
      }
    }
    ctx.globalAlpha = 1
    t += 0.06 * props.speed
    raf = requestAnimationFrame(draw)
  }

  draw()
  ro = new ResizeObserver(resize)
  ro.observe(el)
})

onUnmounted(() => {
  cancelAnimationFrame(raf); ro?.disconnect(); cleanupMouse?.()
})
</script>

<template>
  <canvas ref="canvasRef" style="display:block;width:100%;height:100%;cursor:crosshair" />
</template>
