// packages/vue/src/components/ui/shapes/LightningShape.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'

interface Props {
  class?: string
  size?: number
  strokeWidth?: number
  filled?: boolean
  color?: string
}

const props = withDefaults(defineProps<Props>(), {
  size: 100,
  strokeWidth: 3,
  filled: true,
})
</script>

<template>
  <svg
    :width="size * 0.6"
    :height="size"
    viewBox="0 0 60 100"
    :class="cn('text-warning', props.class)"
  >
    <path
      d="M35 0 L5 55 L25 55 L15 100 L55 40 L35 40 L50 0 Z"
      :fill="filled ? (color || 'currentColor') : 'none'"
      stroke="hsl(var(--foreground))"
      :stroke-width="strokeWidth"
    />
  </svg>
</template>

// packages/react-native/src/shapes/LightningShape.tsx
import React from 'react'
import { Path } from 'react-native-svg'
import { ShapeBase } from './ShapeBase'
import type { ShapeProps } from './types'

export function LightningShape({ size = 100, ...props }: ShapeProps) {
  // Matches web: width = size * 0.6, height = size, viewBox="0 0 60 100"
  return (
    <ShapeBase
      {...props}
      size={size}
      defaultColor="warning"
      viewBox="0 0 60 100"
      svgWidth={size * 0.6}
      svgHeight={size}
    >
      {(fill, stroke, sw) => (
        <Path d="M35 0 L5 55 L25 55 L15 100 L55 40 L35 40 L50 0 Z" fill={fill} stroke={stroke} strokeWidth={sw} />
      )}
    </ShapeBase>
  )
}
