// packages/svelte/src/lib/components/ui/layered-card/layered-card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { type VariantProps } from 'class-variance-authority'
  import { cn } from '$lib/utils.js'
  import { layeredCardVariants } from './layered-card-variants.js'

  type LayeredCardVariants = VariantProps<typeof layeredCardVariants>

  type Props = {
    class?: string
    layers?: LayeredCardVariants['layers']
    offset?: LayeredCardVariants['offset']
    layerColor?: LayeredCardVariants['layerColor']
    interactive?: boolean
    children?: Snippet
  }

  let {
    class: className,
    layers = 'double',
    offset = 'default',
    layerColor = 'default',
    interactive = false,
    children,
  }: Props = $props()

  const offsetSizes: Record<string, number> = { sm: 6, default: 8, lg: 12 }
  const colorClasses: Record<string, string> = {
    default: 'bg-muted',
    primary: 'bg-primary',
    secondary: 'bg-secondary',
    accent: 'bg-accent',
    muted: 'bg-muted',
  }

  const offsetPx = $derived(offsetSizes[offset ?? 'default'])
  const layerCount = $derived(layers === 'single' ? 1 : layers === 'triple' ? 3 : 2)
  const layerBg = $derived(colorClasses[layerColor ?? 'default'])
</script>

<div class={cn(layeredCardVariants({ layers, offset, layerColor }), className)}>
  {#if layerCount >= 3}
    <div
      class={cn('absolute inset-0 border-3 border-foreground', layerBg, 'opacity-50')}
      style="transform: translate({offsetPx * 3}px, {offsetPx * 3}px)"
    ></div>
  {/if}
  {#if layerCount >= 2}
    <div
      class={cn('absolute inset-0 border-3 border-foreground', layerBg, 'opacity-70')}
      style="transform: translate({offsetPx * 2}px, {offsetPx * 2}px)"
    ></div>
  {/if}
  <div
    class={cn('absolute inset-0 border-3 border-foreground', layerBg)}
    style="transform: translate({offsetPx}px, {offsetPx}px)"
  ></div>
  <div
    class={cn(
      'relative border-3 border-foreground bg-card text-card-foreground',
      interactive && 'cursor-pointer transition-transform duration-200 hover:translate-x-[-4px] hover:translate-y-[-4px]'
    )}
  >
    {@render children?.()}
  </div>
</div>

// registry/default/ui/layered-card.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const layeredCardVariants = cva('relative', {
  variants: {
    layers: {
      single: '',
      double: '',
      triple: '',
    },
    offset: {
      sm: '',
      default: '',
      lg: '',
    },
    layerColor: {
      default: '',
      primary: '',
      secondary: '',
      accent: '',
      muted: '',
    },
  },
  defaultVariants: {
    layers: 'double',
    offset: 'default',
    layerColor: 'default',
  },
})

export interface LayeredCardProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof layeredCardVariants> {
  /** Make the card interactive with hover effects */
  interactive?: boolean
}

const LayeredCard = React.forwardRef<HTMLDivElement, LayeredCardProps>(
  ({ className, layers, offset, layerColor, interactive = false, children, ...props }, ref) => {
    // Calculate offsets based on size
    const offsetSizes = {
      sm: 6,
      default: 8,
      lg: 12,
    }
    const offsetPx = offsetSizes[offset || 'default']

    // Get layer count
    const layerCount = layers === 'single' ? 1 : layers === 'triple' ? 3 : 2

    // Get background color class for layers
    const colorClasses = {
      default: 'bg-muted',
      primary: 'bg-primary',
      secondary: 'bg-secondary',
      accent: 'bg-accent',
      muted: 'bg-muted',
    }
    const layerBg = colorClasses[layerColor || 'default']

    return (
      <div
        ref={ref}
        className={cn(layeredCardVariants({ layers, offset, layerColor }), className)}
        {...props}
      >
        {/* Layer 3 (furthest back) */}
        {layerCount >= 3 && (
          <div
            className={cn(
              'absolute inset-0 border-3 border-foreground',
              layerBg,
              'opacity-50'
            )}
            style={{
              transform: `translate(${offsetPx * 3}px, ${offsetPx * 3}px)`,
            }}
          />
        )}

        {/* Layer 2 */}
        {layerCount >= 2 && (
          <div
            className={cn(
              'absolute inset-0 border-3 border-foreground',
              layerBg,
              'opacity-70'
            )}
            style={{
              transform: `translate(${offsetPx * 2}px, ${offsetPx * 2}px)`,
            }}
          />
        )}

        {/* Layer 1 */}
        {layerCount >= 1 && (
          <div
            className={cn('absolute inset-0 border-3 border-foreground', layerBg)}
            style={{
              transform: `translate(${offsetPx}px, ${offsetPx}px)`,
            }}
          />
        )}

        {/* Main card (top layer) */}
        <div
          className={cn(
            'relative border-3 border-foreground bg-card text-card-foreground',
            interactive &&
              'cursor-pointer transition-transform duration-200 hover:translate-x-[-4px] hover:translate-y-[-4px]'
          )}
        >
          {children}
        </div>
      </div>
    )
  }
)
LayeredCard.displayName = 'LayeredCard'

const LayeredCardHeader = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      'flex flex-col space-y-1.5 border-b-3 border-foreground bg-muted p-4',
      className
    )}
    {...props}
  />
))
LayeredCardHeader.displayName = 'LayeredCardHeader'

const LayeredCardTitle = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h3
    ref={ref}
    className={cn('text-xl font-bold uppercase tracking-wide', className)}
    {...props}
  />
))
LayeredCardTitle.displayName = 'LayeredCardTitle'

const LayeredCardDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p ref={ref} className={cn('text-sm text-muted-foreground', className)} {...props} />
))
LayeredCardDescription.displayName = 'LayeredCardDescription'

const LayeredCardContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn('p-4', className)} {...props} />
))
LayeredCardContent.displayName = 'LayeredCardContent'

const LayeredCardFooter = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      'flex items-center border-t-3 border-foreground bg-muted p-4',
      className
    )}
    {...props}
  />
))
LayeredCardFooter.displayName = 'LayeredCardFooter'

export {
  LayeredCard,
  LayeredCardHeader,
  LayeredCardTitle,
  LayeredCardDescription,
  LayeredCardContent,
  LayeredCardFooter,
  layeredCardVariants,
}
