// packages/angular/projects/boldkit/src/lib/components/layered-card/layered-card.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core'
import { CommonModule } from '@angular/common'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '../../utils/cn'

export const layeredCardVariants = cva('relative', {
  variants: {
    layers: {
      single: '',
      double: '',
      triple: '',
    },
    offset: {
      sm: '',
      default: '',
      lg: '',
    },
    layerColor: {
      default: '',
      primary: '',
      secondary: '',
      accent: '',
      muted: '',
    },
  },
  defaultVariants: {
    layers: 'double',
    offset: 'default',
    layerColor: 'default',
  },
})

export type LayeredCardVariants = VariantProps<typeof layeredCardVariants>

@Component({
  selector: 'bk-layered-card',
  standalone: true,
  imports: [CommonModule],
  template: `
    <!-- Layer 3 (furthest back) -->
    <div
      *ngIf="layerCount >= 3"
      [class]="getLayerClass('opacity-50')"
      [style.transform]="'translate(' + (offsetPx * 3) + 'px, ' + (offsetPx * 3) + 'px)'">
    </div>

    <!-- Layer 2 -->
    <div
      *ngIf="layerCount >= 2"
      [class]="getLayerClass('opacity-70')"
      [style.transform]="'translate(' + (offsetPx * 2) + 'px, ' + (offsetPx * 2) + 'px)'">
    </div>

    <!-- Layer 1 -->
    <div
      *ngIf="layerCount >= 1"
      [class]="getLayerClass()"
      [style.transform]="'translate(' + offsetPx + 'px, ' + offsetPx + 'px)'">
    </div>

    <!-- Main card (top layer) -->
    <div [class]="mainCardClass">
      <ng-content></ng-content>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LayeredCardComponent {
  @Input() layers: LayeredCardVariants['layers'] = 'double'
  @Input() offset: LayeredCardVariants['offset'] = 'default'
  @Input() layerColor: LayeredCardVariants['layerColor'] = 'default'
  @Input() interactive: boolean = false
  @Input() class: string = ''

  private offsetSizes = { sm: 6, default: 8, lg: 12 }
  private colorClasses = {
    default: 'bg-muted',
    primary: 'bg-primary',
    secondary: 'bg-secondary',
    accent: 'bg-accent',
    muted: 'bg-muted',
  }

  @HostBinding('class')
  get hostClass(): string {
    return cn(layeredCardVariants({ layers: this.layers, offset: this.offset, layerColor: this.layerColor }), this.class)
  }

  get offsetPx(): number {
    return this.offsetSizes[this.offset || 'default']
  }

  get layerCount(): number {
    return this.layers === 'single' ? 1 : this.layers === 'triple' ? 3 : 2
  }

  get layerBg(): string {
    return this.colorClasses[this.layerColor || 'default']
  }

  getLayerClass(extraClass: string = ''): string {
    return cn('absolute inset-0 border-3 border-foreground', this.layerBg, extraClass)
  }

  get mainCardClass(): string {
    return cn(
      'relative border-3 border-foreground bg-card text-card-foreground',
      this.interactive && 'cursor-pointer transition-transform duration-200 hover:translate-x-[-4px] hover:translate-y-[-4px]'
    )
  }
}

@Component({
  selector: 'bk-layered-card-header',
  standalone: true,
  template: `<ng-content></ng-content>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LayeredCardHeaderComponent {
  @Input() class: string = ''

  @HostBinding('class')
  get hostClass(): string {
    return cn('flex flex-col space-y-1.5 border-b-3 border-foreground bg-muted p-4', this.class)
  }
}

@Component({
  selector: 'bk-layered-card-title',
  standalone: true,
  template: `<ng-content></ng-content>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LayeredCardTitleComponent {
  @Input() class: string = ''

  @HostBinding('class')
  get hostClass(): string {
    return cn('text-xl font-bold uppercase tracking-wide', this.class)
  }
}

@Component({
  selector: 'bk-layered-card-description',
  standalone: true,
  template: `<ng-content></ng-content>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LayeredCardDescriptionComponent {
  @Input() class: string = ''

  @HostBinding('class')
  get hostClass(): string {
    return cn('text-sm text-muted-foreground', this.class)
  }
}

@Component({
  selector: 'bk-layered-card-content',
  standalone: true,
  template: `<ng-content></ng-content>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LayeredCardContentComponent {
  @Input() class: string = ''

  @HostBinding('class')
  get hostClass(): string {
    return cn('p-4', this.class)
  }
}

@Component({
  selector: 'bk-layered-card-footer',
  standalone: true,
  template: `<ng-content></ng-content>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LayeredCardFooterComponent {
  @Input() class: string = ''

  @HostBinding('class')
  get hostClass(): string {
    return cn('flex items-center border-t-3 border-foreground bg-muted p-4', this.class)
  }
}

export const LayeredCardComponents = [
  LayeredCardComponent,
  LayeredCardHeaderComponent,
  LayeredCardTitleComponent,
  LayeredCardDescriptionComponent,
  LayeredCardContentComponent,
  LayeredCardFooterComponent,
]

// registry/default/ui/layered-card.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const layeredCardVariants = cva('relative', {
  variants: {
    layers: {
      single: '',
      double: '',
      triple: '',
    },
    offset: {
      sm: '',
      default: '',
      lg: '',
    },
    layerColor: {
      default: '',
      primary: '',
      secondary: '',
      accent: '',
      muted: '',
    },
  },
  defaultVariants: {
    layers: 'double',
    offset: 'default',
    layerColor: 'default',
  },
})

export interface LayeredCardProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof layeredCardVariants> {
  /** Make the card interactive with hover effects */
  interactive?: boolean
}

const LayeredCard = React.forwardRef<HTMLDivElement, LayeredCardProps>(
  ({ className, layers, offset, layerColor, interactive = false, children, ...props }, ref) => {
    // Calculate offsets based on size
    const offsetSizes = {
      sm: 6,
      default: 8,
      lg: 12,
    }
    const offsetPx = offsetSizes[offset || 'default']

    // Get layer count
    const layerCount = layers === 'single' ? 1 : layers === 'triple' ? 3 : 2

    // Get background color class for layers
    const colorClasses = {
      default: 'bg-muted',
      primary: 'bg-primary',
      secondary: 'bg-secondary',
      accent: 'bg-accent',
      muted: 'bg-muted',
    }
    const layerBg = colorClasses[layerColor || 'default']

    return (
      <div
        ref={ref}
        className={cn(layeredCardVariants({ layers, offset, layerColor }), className)}
        {...props}
      >
        {/* Layer 3 (furthest back) */}
        {layerCount >= 3 && (
          <div
            className={cn(
              'absolute inset-0 border-3 border-foreground',
              layerBg,
              'opacity-50'
            )}
            style={{
              transform: `translate(${offsetPx * 3}px, ${offsetPx * 3}px)`,
            }}
          />
        )}

        {/* Layer 2 */}
        {layerCount >= 2 && (
          <div
            className={cn(
              'absolute inset-0 border-3 border-foreground',
              layerBg,
              'opacity-70'
            )}
            style={{
              transform: `translate(${offsetPx * 2}px, ${offsetPx * 2}px)`,
            }}
          />
        )}

        {/* Layer 1 */}
        {layerCount >= 1 && (
          <div
            className={cn('absolute inset-0 border-3 border-foreground', layerBg)}
            style={{
              transform: `translate(${offsetPx}px, ${offsetPx}px)`,
            }}
          />
        )}

        {/* Main card (top layer) */}
        <div
          className={cn(
            'relative border-3 border-foreground bg-card text-card-foreground',
            interactive &&
              'cursor-pointer transition-transform duration-200 hover:translate-x-[-4px] hover:translate-y-[-4px]'
          )}
        >
          {children}
        </div>
      </div>
    )
  }
)
LayeredCard.displayName = 'LayeredCard'

const LayeredCardHeader = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      'flex flex-col space-y-1.5 border-b-3 border-foreground bg-muted p-4',
      className
    )}
    {...props}
  />
))
LayeredCardHeader.displayName = 'LayeredCardHeader'

const LayeredCardTitle = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h3
    ref={ref}
    className={cn('text-xl font-bold uppercase tracking-wide', className)}
    {...props}
  />
))
LayeredCardTitle.displayName = 'LayeredCardTitle'

const LayeredCardDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p ref={ref} className={cn('text-sm text-muted-foreground', className)} {...props} />
))
LayeredCardDescription.displayName = 'LayeredCardDescription'

const LayeredCardContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn('p-4', className)} {...props} />
))
LayeredCardContent.displayName = 'LayeredCardContent'

const LayeredCardFooter = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      'flex items-center border-t-3 border-foreground bg-muted p-4',
      className
    )}
    {...props}
  />
))
LayeredCardFooter.displayName = 'LayeredCardFooter'

export {
  LayeredCard,
  LayeredCardHeader,
  LayeredCardTitle,
  LayeredCardDescription,
  LayeredCardContent,
  LayeredCardFooter,
  layeredCardVariants,
}
