// packages/react-native/src/shapes/HexagonShape.tsx
import React from 'react'
import { Path } from 'react-native-svg'
import { ShapeBase } from './ShapeBase'
import type { ShapeProps } from './types'

export function HexagonShape(props: ShapeProps) {
  return (
    <ShapeBase {...props} defaultColor="secondary">
      {(fill, stroke, sw) => (
        <Path d="M25 10 L75 10 L95 50 L75 90 L25 90 L5 50 Z" fill={fill} stroke={stroke} strokeWidth={sw} />
      )}
    </ShapeBase>
  )
}

// packages/vue/src/components/ui/shapes/HexagonShape.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'

interface Props {
  class?: string
  size?: number
  strokeWidth?: number
  filled?: boolean
  color?: string
}

const props = withDefaults(defineProps<Props>(), {
  size: 100,
  strokeWidth: 3,
  filled: true,
})
</script>

<template>
  <svg
    :width="size"
    :height="size"
    viewBox="0 0 100 100"
    :class="cn('text-secondary', props.class)"
  >
    <path
      d="M25 10 L75 10 L95 50 L75 90 L25 90 L5 50 Z"
      :fill="filled ? (color || 'currentColor') : 'none'"
      stroke="hsl(var(--foreground))"
      :stroke-width="strokeWidth"
    />
  </svg>
</template>
