// packages/svelte/src/lib/components/ui/progress.svelte
<script lang="ts">
  import { Progress } from 'bits-ui'
  import { cn } from '$lib/utils.js'

  interface Props extends Progress.RootProps {
    class?: string
    value?: number
  }

  let { class: className, value = 0, ...restProps }: Props = $props()
</script>

<Progress.Root
  {value}
  class={cn(
    'relative h-5 w-full overflow-hidden border-3 border-foreground bg-muted shadow-[4px_4px_0px_hsl(var(--shadow-color))]',
    className
  )}
  {...restProps}
>
  <div
    class="h-full w-full flex-1 bg-primary transition-all duration-500 ease-out"
    style="transform: translateX(-{100 - ((value as number) || 0)}%)"
  ></div>
</Progress.Root>

// src/components/ui/progress.tsx
import * as React from 'react'
import * as ProgressPrimitive from '@radix-ui/react-progress'
import { cn } from '@/lib/utils'

const Progress = React.forwardRef<
  React.ElementRef<typeof ProgressPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root>
>(({ className, value, ...props }, ref) => (
  <ProgressPrimitive.Root
    ref={ref}
    className={cn(
      'relative h-5 w-full overflow-hidden border-3 border-foreground bg-muted bk-shadow-sm',
      className
    )}
    {...props}
  >
    <ProgressPrimitive.Indicator
      className="h-full w-full flex-1 bg-primary transition-all"
      style={{ transform: `translateX(-${100 - (value || 0)}%)` }}
    />
  </ProgressPrimitive.Root>
))
Progress.displayName = ProgressPrimitive.Root.displayName

export { Progress }
