// packages/svelte/src/lib/components/ui/rating/rating.svelte
<script lang="ts">
	import { cn } from '$lib/utils.js';
	import StarIcon from '@lucide/svelte/icons/star';
	import HeartIcon from '@lucide/svelte/icons/heart';
	import CircleIcon from '@lucide/svelte/icons/circle';

	type RatingSize = 'sm' | 'md' | 'lg' | 'xl';
	type RatingIcon = 'star' | 'heart' | 'circle';

	type Props = {
		value?: number;
		defaultValue?: number;
		max?: number;
		precision?: 0.5 | 1;
		icon?: RatingIcon;
		size?: RatingSize;
		readOnly?: boolean;
		disabled?: boolean;
		class?: string;
		onchange?: (value: number) => void;
	};

	let {
		value = $bindable(undefined),
		defaultValue = 0,
		max = 5,
		precision = 1,
		icon = 'star',
		size = 'md',
		readOnly = false,
		disabled = false,
		class: className,
		onchange,
	}: Props = $props();

	const sizeClasses: Record<RatingSize, string> = {
		sm: '[&_svg]:h-4 [&_svg]:w-4',
		md: '[&_svg]:h-5 [&_svg]:w-5',
		lg: '[&_svg]:h-6 [&_svg]:w-6',
		xl: '[&_svg]:h-8 [&_svg]:w-8',
	};

	const iconComponents: Record<RatingIcon, typeof StarIcon> = {
		star: StarIcon,
		heart: HeartIcon,
		circle: CircleIcon,
	};

	let internalValue = $state(defaultValue);
	let hoverValue = $state<number | null>(null);

	const isControlled = $derived(value !== undefined);
	const currentValue = $derived(isControlled ? value! : internalValue);
	const displayValue = $derived(hoverValue ?? currentValue);
	const IconComponent = $derived(iconComponents[icon]);

	function handleClick(index: number, isHalf: boolean) {
		if (readOnly || disabled) return;
		const newValue = isHalf && precision === 0.5 ? index + 0.5 : index + 1;
		if (!isControlled) internalValue = newValue;
		value = newValue;
		onchange?.(newValue);
	}

	function handleMouseMove(e: MouseEvent, index: number) {
		if (readOnly || disabled) return;
		const button = (e.target as Element)?.closest('button') as HTMLButtonElement | null;
		if (!button) return;
		const rect = button.getBoundingClientRect();
		const isHalf = e.clientX - rect.left < rect.width / 2;
		hoverValue = isHalf && precision === 0.5 ? index + 0.5 : index + 1;
	}

	function handleMouseLeave() {
		if (readOnly || disabled) return;
		hoverValue = null;
	}

	function handleKeyDown(e: KeyboardEvent) {
		if (readOnly || disabled) return;
		let newValue = currentValue;
		switch (e.key) {
			case 'ArrowRight':
			case 'ArrowUp':
				e.preventDefault();
				newValue = Math.min(currentValue + precision, max);
				break;
			case 'ArrowLeft':
			case 'ArrowDown':
				e.preventDefault();
				newValue = Math.max(currentValue - precision, 0);
				break;
			case 'Home':
				e.preventDefault();
				newValue = 0;
				break;
			case 'End':
				e.preventDefault();
				newValue = max;
				break;
			default:
				return;
		}
		if (!isControlled) internalValue = newValue;
		value = newValue;
		onchange?.(newValue);
	}

	function handleIconClick(e: MouseEvent, index: number) {
		const button = (e.target as Element)?.closest('button') as HTMLButtonElement | null;
		if (!button) return;
		const rect = button.getBoundingClientRect();
		const isHalf = e.clientX - rect.left < rect.width / 2;
		handleClick(index, isHalf);
	}

	function getFillState(index: number) {
		const fillValue = displayValue - index;
		return { isFilled: fillValue >= 1, isHalfFilled: fillValue > 0 && fillValue < 1 };
	}
</script>

<div
	role="radiogroup"
	aria-label="Rating: {currentValue} out of {max}"
	tabindex={readOnly || disabled ? -1 : 0}
	class={cn(
		'flex items-center gap-0.5',
		sizeClasses[size],
		disabled && 'opacity-50 pointer-events-none',
		!readOnly && !disabled && 'cursor-pointer',
		className
	)}
	onkeydown={handleKeyDown}
	onmouseleave={handleMouseLeave}
>
	{#each { length: max } as _, i}
		{@const { isFilled, isHalfFilled } = getFillState(i)}
		<button
			type="button"
			role="radio"
			aria-checked={i < currentValue}
			tabindex={-1}
			disabled={disabled || readOnly}
			class={cn(
				'relative transition-transform duration-150 focus:outline-none',
				!readOnly && !disabled && 'hover:scale-110'
			)}
			onclick={(e) => handleIconClick(e, i)}
			onmousemove={(e) => handleMouseMove(e, i)}
		>
			<IconComponent class="stroke-foreground stroke-2 fill-muted transition-colors duration-150" />
			{#if isFilled || isHalfFilled}
				<IconComponent
					class="absolute inset-0 stroke-foreground stroke-2 fill-primary transition-colors duration-150"
					style={isHalfFilled ? 'clip-path: polygon(0 0, 50% 0, 50% 100%, 0 100%)' : undefined}
				/>
			{/if}
		</button>
	{/each}
</div>

// src/components/ui/rating.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'
import { Star, Heart, Circle } from 'lucide-react'

const ratingVariants = cva('flex items-center gap-0.5', {
  variants: {
    size: {
      sm: '[&_svg]:h-4 [&_svg]:w-4',
      md: '[&_svg]:h-5 [&_svg]:w-5',
      lg: '[&_svg]:h-6 [&_svg]:w-6',
      xl: '[&_svg]:h-8 [&_svg]:w-8',
    },
  },
  defaultVariants: {
    size: 'md',
  },
})

const iconMap = {
  star: Star,
  heart: Heart,
  circle: Circle,
}

export interface RatingProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'>,
    VariantProps<typeof ratingVariants> {
  value?: number
  defaultValue?: number
  max?: number
  precision?: 0.5 | 1
  icon?: 'star' | 'heart' | 'circle'
  readOnly?: boolean
  disabled?: boolean
  onChange?: (value: number) => void
  onHoverChange?: (value: number | null) => void
}

const Rating = React.forwardRef<HTMLDivElement, RatingProps>(
  (
    {
      value: controlledValue,
      defaultValue = 0,
      max = 5,
      precision = 1,
      icon = 'star',
      size,
      readOnly = false,
      disabled = false,
      onChange,
      onHoverChange,
      className,
      ...props
    },
    ref
  ) => {
    const [uncontrolledValue, setUncontrolledValue] = React.useState(defaultValue)
    const [hoverValue, setHoverValue] = React.useState<number | null>(null)

    const isControlled = controlledValue !== undefined
    const currentValue = isControlled ? controlledValue : uncontrolledValue
    const displayValue = hoverValue ?? currentValue

    const Icon = iconMap[icon]

    const handleClick = (index: number, isHalf: boolean) => {
      if (readOnly || disabled) return

      const newValue = isHalf && precision === 0.5 ? index + 0.5 : index + 1

      if (!isControlled) {
        setUncontrolledValue(newValue)
      }
      onChange?.(newValue)
    }

    const handleMouseMove = (
      e: React.MouseEvent<HTMLButtonElement>,
      index: number
    ) => {
      if (readOnly || disabled) return

      const rect = e.currentTarget.getBoundingClientRect()
      const isHalf = e.clientX - rect.left < rect.width / 2

      const newHoverValue =
        isHalf && precision === 0.5 ? index + 0.5 : index + 1
      setHoverValue(newHoverValue)
      onHoverChange?.(newHoverValue)
    }

    const handleMouseLeave = () => {
      if (readOnly || disabled) return
      setHoverValue(null)
      onHoverChange?.(null)
    }

    const handleKeyDown = (e: React.KeyboardEvent) => {
      if (readOnly || disabled) return

      let newValue = currentValue

      switch (e.key) {
        case 'ArrowRight':
        case 'ArrowUp':
          e.preventDefault()
          newValue = Math.min(currentValue + precision, max)
          break
        case 'ArrowLeft':
        case 'ArrowDown':
          e.preventDefault()
          newValue = Math.max(currentValue - precision, 0)
          break
        case 'Home':
          e.preventDefault()
          newValue = 0
          break
        case 'End':
          e.preventDefault()
          newValue = max
          break
        default:
          return
      }

      if (!isControlled) {
        setUncontrolledValue(newValue)
      }
      onChange?.(newValue)
    }

    return (
      <div
        ref={ref}
        role="radiogroup"
        aria-label="Rating"
        tabIndex={readOnly || disabled ? -1 : 0}
        onKeyDown={handleKeyDown}
        onMouseLeave={handleMouseLeave}
        className={cn(
          ratingVariants({ size }),
          disabled && 'opacity-50 pointer-events-none',
          !readOnly && !disabled && 'cursor-pointer',
          className
        )}
        {...props}
      >
        {Array.from({ length: max }, (_, index) => {
          const fillValue = displayValue - index
          const isFilled = fillValue >= 1
          const isHalfFilled = fillValue > 0 && fillValue < 1

          return (
            <button
              key={`star-${index}`}
              type="button"
              role="radio"
              aria-checked={index < currentValue}
              aria-label={`${index + 1} ${icon === 'star' ? 'star' : icon === 'heart' ? 'heart' : 'circle'}`}
              tabIndex={-1}
              disabled={disabled || readOnly}
              onClick={(e) => {
                const rect = e.currentTarget.getBoundingClientRect()
                const isHalf = e.clientX - rect.left < rect.width / 2
                handleClick(index, isHalf)
              }}
              onMouseMove={(e) => handleMouseMove(e, index)}
              className={cn(
                'relative transition-transform duration-150 focus:outline-none',
                !readOnly && !disabled && 'hover:scale-110'
              )}
            >
              {/* Empty icon (background) */}
              <Icon
                className={cn(
                  'stroke-foreground stroke-[2px] fill-muted transition-colors duration-150'
                )}
              />

              {/* Filled icon (overlay) */}
              {(isFilled || isHalfFilled) && (
                <Icon
                  className={cn(
                    'absolute inset-0 stroke-foreground stroke-[2px] fill-primary transition-colors duration-150'
                  )}
                  style={
                    isHalfFilled
                      ? {
                          clipPath: 'polygon(0 0, 50% 0, 50% 100%, 0 100%)',
                        }
                      : undefined
                  }
                />
              )}
            </button>
          )
        })}
      </div>
    )
  }
)
Rating.displayName = 'Rating'

export { Rating, ratingVariants }
